var snapsvg = require("snapsvg");
require("./system");
require("./paper");
require("./snap-tests");
require("./class");
require("./primitives");
require("./colors");
require("./attrs");
require("./attradd");
require("./path");
require("./element");
require("./gradients");
require("./set");
require("./filter");
require("./matrix");
require("./mina");